### ISSUE TITLE
Using proxy?

### ISSUE THREAD

**Issue by valexandersaulys** [dbaty/Basket#10]
Hello,

I'm currently behind a company proxy. Normally I can use the `HTTP_PROXY` and `HTTPS_PROXY` when using pip. Then, pip works as expected.

But Basket does not work like this.

Any thoughts or solutions? Am I missing something obvious?

Thanks so much for building such a useful library!
Vincent

**Comment by dbaty** [comment]
Hi,

There is indeed no particular support for proxies in Basket. I would think that setting the usual environment variables works, but it does not seem so. Another user started to work on proxy support, see pull request #3. As you can see from my comments there, it was not quite ready to merge. It's been lingering since June 2015 so it's unlikely that the author of this pull request is going to complete it. It would be a good starting point if you want to try and contribute.

**Comment by valexandersaulys** [comment]
Ok!

I figure that it may be easier to just use `pip download <name of package>` into some directory, tarball that, and then run `pip install *.whl` to get all the required dependencies.

Alternatively, one could use [jFrog's Artifactory to host a PyPi mirror](https://www.jfrog.com/confluence/display/RTF/PyPI+Repositories). I know its not open source, but given this is something I need for corporate, the solution is good enough for me. 

Anyways, thanks for the speedy response! I wanted to leave something here in case somebody else had the same issue.

**Comment by dbaty** [comment]
Basket does not work anymore and has not been supported for years (as can be seen in this very issue). I just added a note in the README about that, with a migration guide to pip: https://github.com/dbaty/Basket#readme.

Hope it helps! :)
